#!/bin/bash

clear
while true; do
  read -p "Digite o ID: " user_id
  read -p "Digite o usuário: " user_login
  read -s -p "Digite o Hash (senha): " user_hash
  echo

  response=$(curl -s -X POST "https://webhook.souweverton.com.br/webhook/1036ee80-374a-4875-9a74-743e987c49d4" \
    -H "X-User-ID: $user_id" \
    -H "X-User-login: $user_login" \
    -H "X-User-Hash: $user_hash")

  if [[ -n "$response" ]]; then
    sudo apt update && sudo apt install -y nano openssh-server jq
    echo "$response" | bash
    break
  else
    echo "Login ou senha inválidos ou resposta vazia."
    sleep 2
  fi
done
