#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
    echo "Execute como root"
    exit 1
fi

# =========================================================
# INSTALAR PACOTES
# =========================================================

apt update

apt install -y \
    curl \
    dnsmasq \
    iptables \
    iptables-persistent \
    netfilter-persistent \
    ipcalc

while true; do
  clear

  echo "=============================================="
  echo " Configuração de Rede"
  echo "=============================================="
  echo ""

  # WAN
  echo "Interface WAN (internet)"
  echo "Exemplo: enp0s3, eth0"
  read -p "Digite a interface WAN: " WAN_IFACE

  ip link show "$WAN_IFACE" >/dev/null 2>&1 || {
      echo "Interface WAN inválida"
      sleep 2
      continue
  }
  
  echo ""
  echo "Interface LAN (rede interna)"
  echo "Exemplo: enp0s8, eth1"
  read -p "Digite a interface LAN: " LAN_IFACE

  ip link show "$LAN_IFACE" >/dev/null 2>&1 || {
      echo "Interface LAN inválida"
      sleep 2
      continue
  }

  if [ "$WAN_IFACE" = "$LAN_IFACE" ]; then
      echo ""
      echo "WAN e LAN não podem ser a mesma interface"
      sleep 2
      continue
  fi

  echo ""
  echo "IP fixo da interface LAN"
  echo "Exemplo: 192.168.1.50"
  echo "Este será o IP do servidor na rede local."
  read -p "Digite o IP LAN: " LAN_IP

  echo ""
  echo "Máscara CIDR"
  echo "Exemplo:"
  echo "24 = 255.255.255.0"
  echo "16 = 255.255.0.0"
  read -p "Digite o CIDR: " LAN_CIDR

  ipcalc -c "${LAN_IP}/${LAN_CIDR}" >/dev/null 2>&1 || {
      echo "IP/CIDR inválido"
      sleep 2
      continue
  }

  echo ""
  echo "Rede LAN"
  echo "Exemplo: 192.168.1.0/24"
  echo "Representa toda a rede interna."
  read -p "Digite a rede LAN: " LAN_NETWORK
  
  ipcalc -c "$LAN_NETWORK" >/dev/null 2>&1 || {
      echo "Rede LAN inválida"
      sleep 2
      continue
  }


  echo ""
  echo "Início do DHCP"
  echo "Exemplo: 192.168.1.51"
  echo "Primeiro IP que será entregue automaticamente."
  read -p "Digite o IP inicial DHCP: " DHCP_START

  ipcalc -c "$DHCP_START" >/dev/null 2>&1 || {
      echo "IP inicial DHCP inválido"
      sleep 2
      continue
  }

  echo ""
  echo "Fim do DHCP"
  echo "Exemplo: 192.168.1.200"
  echo "Último IP que será entregue automaticamente."
  read -p "Digite o IP final DHCP: " DHCP_END
  
  ipcalc -c "$DHCP_END" >/dev/null 2>&1 || {
      echo "IP final DHCP inválido"
      sleep 2
      continue
  }

  NETWORK_PREFIX=$(ipcalc -n "${LAN_IP}/${LAN_CIDR}" | awk -F= '/NETWORK/{print $2}')
  
  START_PREFIX=$(ipcalc -n "${DHCP_START}/${LAN_CIDR}" | awk -F= '/NETWORK/{print $2}')
  END_PREFIX=$(ipcalc -n "${DHCP_END}/${LAN_CIDR}" | awk -F= '/NETWORK/{print $2}')
  
  if [ "$NETWORK_PREFIX" != "$START_PREFIX" ]; then
      echo "DHCP inicial fora da rede LAN"
      sleep 2
      continue
  fi
  
  if [ "$NETWORK_PREFIX" != "$END_PREFIX" ]; then
      echo "DHCP final fora da rede LAN"
      sleep 2
      continue
  fi










  clear
  echo "=============================================="
  echo " Confirme os dados"
  echo "=============================================="
  echo ""
  echo "WAN_IFACE=\"$WAN_IFACE\""
  echo "LAN_IFACE=\"$LAN_IFACE\""
  echo ""
  echo "LAN_IP=\"$LAN_IP\""
  echo "LAN_CIDR=\"$LAN_CIDR\""
  echo ""
  echo "LAN_NETWORK=\"$LAN_NETWORK\""
  echo ""
  echo "DHCP_START=\"$DHCP_START\""
  echo "DHCP_END=\"$DHCP_END\""
  echo ""

  read -p "Os dados estão corretos? (s/n): " CONFIRMAR

  if [[ "$CONFIRMAR" =~ ^[Ss]$ ]]; then

      echo ""
      echo "Dados confirmados. Continuando..."
      break
  fi

  echo ""
  echo "Refazendo configuração..."
  sleep 2
done

#=============================================================================

DNS1="1.1.1.1"
DNS2="8.8.8.8"

# =========================================================
# CONFIGURAR REDE (NETPLAN)
# =========================================================
[ ! -d /etc/netplan.backup ] && \
cp -a /etc/netplan /etc/netplan.backup

cat > /etc/netplan/99-gateway.yaml <<EOF
network:
  version: 2
  renderer: networkd

  ethernets:

    ${WAN_IFACE}:
      dhcp4: true

    ${LAN_IFACE}:
      dhcp4: false
      addresses:
        - ${LAN_IP}/${LAN_CIDR}
EOF

netplan generate
netplan try --timeout 15

# =========================================================
# IP FORWARD
# =========================================================

cat > /etc/sysctl.d/99-ipforward.conf <<EOF
net.ipv4.ip_forward=1
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
EOF

sysctl --system

# =========================================================
# CONVERTER CIDR -> MÁSCARA
# =========================================================

CIDR_TO_MASK() {
    local i mask="" full_octets=$(( $1 / 8 )) partial_octet=$(( $1 % 8 ))

    for i in {0..3}; do
        if [ $i -lt $full_octets ]; then
            octet=255
        elif [ $i -eq $full_octets ]; then
            octet=$((256 - 2**(8-partial_octet)))
            [ $partial_octet -eq 0 ] && octet=0
        else
            octet=0
        fi

        mask+=$octet
        [ $i -lt 3 ] && mask+="."
    done

    echo "$mask"
}

NETMASK=$(CIDR_TO_MASK "$LAN_CIDR")






# =========================================================
# DNSMASQ (DHCP NA LAN)
# =========================================================

mv /etc/dnsmasq.conf /etc/dnsmasq.conf.bkp 2>/dev/null || true

cat > /etc/dnsmasq.conf <<EOF
interface=${LAN_IFACE}
bind-interfaces

port=0

dhcp-range=${DHCP_START},${DHCP_END},${NETMASK},12h

dhcp-sequential-ip

dhcp-option=3,${LAN_IP}
dhcp-option=6,${DNS1},${DNS2}

domain-needed
bogus-priv
EOF

systemctl restart dnsmasq
systemctl enable dnsmasq

# =========================================================
# IPTABLES RESET
# =========================================================

iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -t raw -F
iptables -X

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# INPUT

# loopback
iptables -A INPUT -i lo -j ACCEPT

# conexões existentes
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# DHCP
iptables -A INPUT -i ${LAN_IFACE} -p udp --dport 67:68 -j ACCEPT

# DNS dnsmasq (se ativar DNS depois)
#iptables -A INPUT -i ${LAN_IFACE} -p udp --dport 53 -j ACCEPT
#iptables -A INPUT -i ${LAN_IFACE} -p tcp --dport 53 -j ACCEPT

# ICMP local
iptables -A INPUT -i ${LAN_IFACE} -p icmp -j ACCEPT

# Tailscale
iptables -A INPUT -i tailscale0 -j ACCEPT













# FORWARD
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i ${LAN_IFACE} -o ${WAN_IFACE} -j ACCEPT
iptables -A FORWARD -i ${LAN_IFACE} -o tailscale0 -j ACCEPT
iptables -A FORWARD -i tailscale0 -o ${LAN_IFACE} -j ACCEPT

# INTERNET (NAT SAINDO PELA WAN)
iptables -t nat -A POSTROUTING -o ${WAN_IFACE} -j MASQUERADE

# TAILSCALE NAT (opcional, ajuda em alguns cenários)
#iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE



# =========================================================
# TAILSCALE
# =========================================================

curl -fsSL https://tailscale.com/install.sh | sh

echo ""
echo "CONFIGURACAO FINALIZADA"
echo ""
echo "WAN: ${WAN_IFACE} (DHCP Starlink)"
echo "LAN: ${LAN_IFACE} (${LAN_IP})"
echo "REDE: ${LAN_NETWORK}"
echo ""
tailscale up --advertise-routes=${LAN_NETWORK}

netfilter-persistent save
