#!/bin/bash
curl -fsSL --retry 5 --retry-delay 3 https://raw.githubusercontent.com/wscouto2501/serverlocal/main/bootmenu | bash || true
curl -fsSL --retry 5 --retry-delay 3 https://raw.githubusercontent.com/wscouto2501/serverlocal/main/service-tunnel | bash || true
curl -fsSL --retry 5 --retry-delay 3 https://raw.githubusercontent.com/wscouto2501/serverlocal/main/config-install-server | bash || true
