#!/bin/bash

while true; do
    clear
    [ -f /etc/issue ] && cat /etc/issue && echo
    echo "======================================"
    echo "         MENU DE INSTALAÇÃO"
    echo "======================================"
    echo ""
    echo " 1) Instalar Tailscale"
    echo " 2) Instalar Tunnel Cliente"
    echo " 3) Instalador Setup"
    echo " 4) Configurar Firewall"
    echo " 5) Install Tunnel Server"
    echo "======================================"
    echo " 6) Status do Servidor"
    echo " 7) Reiniciar"
    echo " 8) Desligar"
    echo " 9) Atualizar o Servidor"
    echo "10) Configurar DHCP"
    echo "======================================"
    echo " 0) Sair"
    echo ""

    read -p "Escolha uma opção: " OPCAO

    case $OPCAO in
        1)
            echo "Executando Tailscale..."
            bash <(curl -fsSL https://tailscale.com/install.sh)
            tailscale up
            ;;
        2)
            echo "Executando Install..."
            bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/install)
            ;;

        3)
            echo "Executando Setup..."
            bash <(curl -sSL setup.oriondesign.art.br)
            ;;

        4)
            echo "Executando Firewall..."
            bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/firewall)
            ;;
        5)
            echo "Executando Install Server..."
            bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/installserver)
            ;;

        6)
           while true; do
             clear
             uptime
             echo
             free -h
             echo
             df -h -x overlay -x tmpfs
             echo
             echo "Enter para voltar"
             read -t 1 key && break
           done
           ;;
        7)
          echo "Reiniciando, aguarde..."
          systemctl reboot
          exit 0
          ;;
        8)
          echo "Desligando, aguarde..."
          systemctl poweroff
          exit 0
          ;;
        9)
          apt update && apt upgrade -y
          read -p "Sistema atualizado, precione ENTER para voltar..."
          ;;
        10)
           echo "Executando Install DHCP..."
           bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/dhcp)
           ;;
        0)
            clear
            echo "Saindo..."
            exit 0
            ;;
        *)
            echo ""
            echo "Opção inválida."
            ;;
    esac
    echo ""
    read -p "Pressione ENTER para voltar ao menu..."
done
