#!/bin/bash

while true; do
    clear
    [ -f /etc/issue ] && cat /etc/issue && echo
    echo "======================================"
    echo "         MENU DE INSTALAÇÃO"
    echo "======================================"
    echo ""
    echo " 1) Instalar Tailscale"
    echo " 2) Install Tunnel Server"
    echo " 3) Instalador Setup"
    echo " 4) Configurar Firewall"
    echo "======================================"
    echo " 5) Status do Servidor"
    echo " 6) Reiniciar"
    echo " 7) Desligar"
    echo " 8) Atualizar o Servidor"
    echo "======================================"
    echo " 9) Configurar DHCP"
    echo "======================================"
    echo "10) Instalar Php + Mysql"
    echo "11) Configurar Lavarel"
    echo "======================================"
    echo " 0) Sair"
    echo ""

    read -p "Escolha uma opção: " OPCAO

    case $OPCAO in
        1)
            echo "Executando Tailscale..."
            bash <(curl -fsSL https://tailscale.com/install.sh)
            tailscale up
            ;;
        2)
            echo "Executando Install Server..."
            bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/installserver)
            ;;
        3)
            echo "Executando Setup..."
            bash <(curl -sSL setup.oriondesign.art.br)
            ;;

        4)
            echo "Executando Firewall..."
            bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/firewall)
            ;;


        5)
           while true; do
             clear
             uptime
             echo
             free -h
             echo
             df -h -x overlay -x tmpfs
             echo
             echo "Enter para voltar"
             read -t 1 key && break
           done
           ;;
        6)
          echo "Reiniciando, aguarde..."
          systemctl reboot
          exit 0
          ;;
        7)
          echo "Desligando, aguarde..."
          systemctl poweroff
          exit 0
          ;;
        8)
          apt update && apt upgrade -y
          read -p "Sistema atualizado, precione ENTER para voltar..."
          ;;
        9)
           echo "Executando Install DHCP..."
           bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/dhcp)
           ;;
        10)
            if command -v docker &> /dev/null
            then
                echo "Docker encontrado. Executando Install PHP + MySQL..."
                bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/php_mysql)
            else
                echo "Docker não instalado. Instale o Docker antes de continuar. utilizando a opção 3) Instalador Setup"
                exit 1
            fi
            ;;
        11)
           echo "Executando configuração Lavarel."
           bash <(curl -fsSL https://raw.githubusercontent.com/wscouto2501/serverlocal/main/laravel)
           ;;
        0)
            clear
            echo "Saindo..."
            exit 0
            ;;
        *)
            echo ""
            echo "Opção inválida."
            ;;
    esac
    echo ""
    read -p "Pressione ENTER para voltar ao menu..."
done
